name: Android Build

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: "3.10"  # Must be <3.12 for faiss-cpu
  FLUTTER_VERSION: "3.27.4"

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel
          pip install -r requirements.txt --use-deprecated=legacy-resolver
          pip check || true  # Identify conflicts without failing

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable

      - name: Setup Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Configure Android SDK
        run: |
          mkdir -p ~/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d ~/android-sdk/cmdline-tools
          mv ~/android-sdk/cmdline-tools/cmdline-tools ~/android-sdk/cmdline-tools/latest
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          
          # Accept all licenses
          yes | ~/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
          flutter doctor --android-licenses

      - name: Install Build Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build libgtk-3-dev clang cmake

      - name: Build APK
        run: |
          flutter config --no-analytics
          flet build apk --verbose \
            --build-number=$BUILD_NUMBER \
            --build-version=$BUILD_VERSION

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk-artifact
          path: build/apk/
          if-no-files-found: error
